version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: companies_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=companies_db
      - DB_HOST=db
    ports:
      - "30000:30000"
    volumes:
      - .:/app
    restart: always
volumes:
  db-data:
